#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx, setting it to listen on port 80, and
# serving a page that contains "Holberton School"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
     sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index.html
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index.html with required content
echo -e "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Reloading Nginx to apply changes (not using systemctl)
sudo nginx -s reload

echo -e "\nCompleted. ✅\n"
